version: '3'
services:

  forwarder:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      --log.level=trace
      --proxy.bind=:8443
      --proxy.allow=0.0.0.0/0
      --proxy.upstream-url=http://superproxy.com:8080
      --proxy.user=
      --proxy.pass=
      --filter.zones=api.ipify.org
      --exclude.hostnames=ipify.org
    ports:
    - "8443:8443"

  machine:
    build:
      context: .
      dockerfile: e2e/Dockerfile
    volumes:
      - .:/go/src/github.com/mysteriumnetwork/openvpn-forwarder
    cap_add:
    - NET_ADMIN
    - NET_RAW

  haproxy-forwarder:
    image: haproxy
    volumes:
      - ./e2e/haproxy-forwarder:/usr/local/etc/haproxy
    ports:
    - "18080:18080"
    - "19999:19999"

  haproxy-gateway:
    image: haproxy
    volumes:
      - ./e2e/haproxy-gateway:/usr/local/etc/haproxy
    ports:
    - "28080:28080"
    - "29999:29999"